# Generated by Django 5.2.5 on 2025-08-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='passenger',
            index=models.Index(fields=['documento'], name='passengers__documen_a26598_idx'),
        ),
        migrations.AddIndex(
            model_name='passenger',
            index=models.Index(fields=['email'], name='passengers__email_42847c_idx'),
        ),
    ]
