# Generated by Django 5.2.5 on 2025-08-13 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('capacidad', models.PositiveIntegerField()),
                ('filas', models.PositiveIntegerField()),
                ('columnas', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=5)),
                ('fila', models.PositiveIntegerField()),
                ('columna', models.CharField(max_length=1)),
                ('tipo', models.CharField(choices=[('ECO', 'Económica'), ('BUS', 'Business'), ('PRE', 'Premium')], default='ECO', max_length=3)),
                ('estado', models.CharField(choices=[('DISP', 'Disponible'), ('RES', 'Reservado'), ('OCU', 'Ocupado')], default='DISP', max_length=4)),
                ('avion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='fleet.airplane')),
            ],
            options={
                'indexes': [models.Index(fields=['avion', 'numero'], name='fleet_seat_avion_i_d3fd59_idx')],
                'unique_together': {('avion', 'numero')},
            },
        ),
    ]
