# Generated by Django 5.2.5 on 2025-08-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='anio_fabricacion',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airplane',
            name='fabricante',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='airplane',
            name='matricula',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='airplane',
            name='notas_tecnicas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airplane',
            name='ultimo_mantenimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
