# Generated by Django 5.2.5 on 2025-08-13 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        ('flights', '0001_initial'),
        ('passengers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('RES', 'Reservado'), ('PAG', 'Pagado'), ('CAN', 'Cancelado')], default='RES', max_length=3)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo_reserva', models.CharField(editable=False, max_length=12, unique=True)),
                ('asiento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reserva', to='fleet.seat')),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='passengers.passenger')),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='flights.flight')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barra', models.CharField(max_length=32, unique=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('EMI', 'Emitido'), ('ANU', 'Anulado')], default='EMI', max_length=3)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boleto', to='booking.reservation')),
            ],
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('vuelo', 'pasajero'), name='unique_passenger_per_flight'),
        ),
    ]
