# Generated by Django 5.2.5 on 2025-08-13 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=80)),
                ('destino', models.CharField(max_length=80)),
                ('fecha_salida', models.DateTimeField()),
                ('fecha_llegada', models.DateTimeField()),
                ('duracion', models.DurationField()),
                ('estado', models.CharField(choices=[('PROG', 'Programado'), ('ABOR', 'Abordando'), ('ENVO', 'En vuelo'), ('CANC', 'Cancelado'), ('FIN', 'Finalizado')], default='PROG', max_length=5)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vuelos', to='fleet.airplane')),
            ],
            options={
                'ordering': ['fecha_salida'],
                'indexes': [models.Index(fields=['origen', 'destino', 'fecha_salida'], name='flights_fli_origen_f2fe16_idx')],
            },
        ),
    ]
