# Generated by Django 5.2.5 on 2025-08-13 20:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='managers',
            field=models.ManyToManyField(blank=True, help_text='Usuarios que gestionan este vuelo', related_name='flights_managed', to=settings.AUTH_USER_MODEL),
        ),
    ]
